name: full-convert

on:
  push:
    branches:
      - master
      - draft

jobs:

  test-convert:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install -y git jq python3-xlrd python3-pandas 

      - name: fetch code, conv it
        run: |
          sh -exc " \
          PATH=$PWD:$PATH;\
          conv.sh all; \
          "

